["protostar.config"]
protostar_version = "0.3.0"

["protostar.project"]
libs_path = "lib"

["protostar.test"]
disable-hint-validation = true

["protostar.shared_command_configs"]
cairo_path = [
    "./lib/cairo_contracts/src"
]


["protostar.contracts"]
main = [
    "src/main.cairo",
]
ERC20MintableBurnable = [
    "src/tokens/ERC20MintableBurnable.cairo",
]
SuperToken = [
    "src/tokens/SuperToken.cairo",
]
core = [
    "src/tokens/core.cairo",
]
