["protostar.config"]
protostar_version = "0.3.0"

["protostar.project"]
libs_path = "lib"

["protostar.test"]
disable-hint-validation = true

["protostar.shared_command_configs"]
cairo_path = [
    "./lib/cairo_contracts/src"
]

["protostar.contracts"]
main = [
    "src/main.cairo",
]
m_token = [
    "src/m_token.cairo",
]
